version: '3.6'

services:

  spider:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seewaldEpisodes
    environment:
      - SLACK_TOKEN=admin
      - SLACK_CHANNEL=admin
    restart: on-failure
    healthcheck:
      test: "exit 0"
