version: '3.6'

services:

  spider:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seewaldEpisodes
    env_file:
      - .env
    restart: on-failure
    healthcheck:
      test: "exit 0"
