version: '3.6'

services:

  rest:
    build:
      context: .
      dockerfile: Dockerfile.rest
    container_name: charging_api-rest
    environment:
      - SLACK_TOKEN=admin
      - SLACK_CHANNEL=admin
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - db
    healthcheck:
      test: "exit 0"
