version: '3.6'

services:

  spider:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seewaldEpisodes
    environment:
      - SLACK_TOKEN=${SLACK_TOKEN}
      - SLACK_CHANNEL=${$SLACK_CHANNEL}
    restart: on-failure
    healthcheck:
      test: "exit 0"
